# docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - data
    restart: always

  data:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
networks:
  app-network:
    driver: bridge